### ISSUE TITLE
Issue 1: User can self select color or select a color by random

### ISSUE THREAD

**Issue by jennydtran** [jennydtran/color-cookbook#1]
## 💰 Motivation

Users like to be able to pick their own color or have one chosen at random if they don't know where to start!

## 📐 Plan

Create a page where a user can select a color (or have a color selected for them). 

## 🖼️ Wireframe

![Screen Shot 2020-11-10 at 10 16 33 AM](https://user-images.githubusercontent.com/71470231/98714515-d8127e80-233d-11eb-9c8f-1c4e488001fb.png)

## ✅ Task List
Home page
- [x] Pick a nice font pair from Google Fonts for headings and body text.
- [x] Pick a nice accent color.
- [x] Create a simple HTML for background, body, and heading and button.
- [x] Create a background.
- [x] Add CSS.

Color picker page
- [x] Create a simple HTML for background, body, and buttons, navigation.
- [x] Add CSS.
- [x] Make sure color picker works.

JavaScript
- [x] Button click on home page should swap view to color picker page.
- [x] Add link to dropper icon.
- [x] AddEventListener for 'submit' on Select button.
- [x] AddEventListener for 'click' on Random button.
- [x] Random button should get the random data color from API site.

Finish up
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again.
