### ISSUE TITLE
Issue 2: User can view color data.

### ISSUE THREAD

**Issue by jennydtran** [jennydtran/color-cookbook#2]
## 💰 Motivation

Users can view the data for selected color and decide whether or not to save, or view the color schemes.

## 📐 Plan

Create a page where a user can decide what to do with the selected color. 

## 🖼️ Wireframe

![Screen Shot 2020-11-10 at 10 35 13 AM](https://user-images.githubusercontent.com/71470231/98716455-70116780-2340-11eb-8d83-ab0dcc58eed5.png)

## ✅ Task List
- [x] Use HTML and CSS to build out color data section.
- [x] When the select button or random button is clicked

> - [x] Data object properties should be updated with the properties from the API object
> - [x] Use css.styles to update the background-color of the color text box
> - [x] RGB, HSL, and HEX values should be updated

- [x] Build out the save button
- [x] Make sure data is saved (stringify, parseJSON)

Finish up
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again.
