### ISSUE TITLE
Issue 3: User can select and view a color scheme for selected color.

### ISSUE THREAD

**Issue by jennydtran** [jennydtran/color-cookbook#3]
## 💰 Motivation

Users like to see color schemes of a color to help them decide on the colors for a project!

## 📐 Plan

Create a page where a user can select and view a color scheme. 

## 🖼️ Wireframe

![Screen Shot 2020-11-10 at 10 36 53 AM](https://user-images.githubusercontent.com/71470231/98716591-ad75f500-2340-11eb-9dd7-86d50207711e.png)

## ✅ Task List
- [x] Build out HTML, CSS for the section

> - [x] Dropdown list for the schemes
> - [x] Color data section for color
> - [x] Div for colors
> - [x] Make color divs clickable

- [x] Color data should get updated when user clicks on the color div
- [x] Option to save color scheme
- [x] If color is saved, should get pushed to data.schemes

Finish up
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again.
