### ISSUE TITLE
Issue 4: Users can view saved colors or color scheme.

### ISSUE THREAD

**Issue by jennydtran** [jennydtran/color-cookbook#4]
## 💰 Motivation

Users should be able to refer back to a color or color scheme that they saved.

## 📐 Plan

Create a page where a user view saved colors or color schemes. 

## 🖼️ Wireframe

![Screen Shot 2020-11-10 at 10 38 25 AM](https://user-images.githubusercontent.com/71470231/98716733-eca44600-2340-11eb-8119-051a20588cd9.png)

## ✅ Task List
Build out HTML & CSS
- [x] Add a div container and separate data-view for colorbook section
- [x] Create a section for saved colors (a list)
- [x] Create a section for saved themes (a list)
- [x] Add CSS

JavaScript
- [x] Create a function to create a dom Tree
- [x] Append to list

Finish up
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again.
